version: '3'

services:
  host4:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    privileged: true
    ports:
      - "10022:22"
    volumes:
      - ./ssh/conf/ssh_config:/etc/ssh/ssh_config
      - ./ssh/conf/sshd_config:/etc/ssh/sshd_config
    networks:
      route9:
        ipv4_address: 192.168.9.2
  router1:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    privileged: true
    networks:
      route9:
        ipv4_address: 192.168.9.10
      route8:
        ipv4_address: 192.168.8.20
  router2:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    privileged: true
    networks:
      route8:
        ipv4_address: 192.168.8.10
      route1:
        ipv4_address: 192.168.1.10
  host5:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    privileged: true
    networks:
      route1:
        ipv4_address: 192.168.1.2
  web:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      route9:
        ipv4_address: 192.168.9.30
  host10:
    image: frrouting/frr:v8.3.1
    networks:
      route9:
        ipv4_address: 192.168.9.100
  host20:
    image: frrouting/frr:v8.3.1
    networks:
      route1:
        ipv4_address: 192.168.1.100
  host30:
    image: frrouting/frr:v8.3.1
    networks:
      route8:
        ipv4_address: 192.168.8.100

networks:
  route9:
    ipam:
      driver: default
      config:
        - subnet: 192.168.9.0/24
  route1:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
  route8:
    ipam:
      driver: default
      config:
        - subnet: 192.168.8.0/24